matrix:
  include:
    - language: python
      python: 3.6
      addons:
        postgresql: "9.5"
      services:
        - postgresql
      install:
        - pip install -r requirements.txt
      before_script:
        - psql -c 'create database timebank_app;' -U postgres
        - psql -c "CREATE USER timebank WITH PASSWORD 'DEBUG';" -U postgres
        - psql -c "ALTER USER timebank CREATEDB;" -U postgres
      script:
        - python timebank_site/manage.py makemigrations
        - python timebank_site/manage.py migrate
        - python timebank_site/manage.py migrate --run-syncdb
        - python timebank_site/manage.py test timebank_app.tests

    # - language: android
    #   jdk: oraclejdk8
    #   android:
    #     components:
    #       - tools
    #       - android-25
    #       - build-tools-25.0.3
    #   before_script:
    #     - cd android/AppName
    #   script:
    #     - ./gradlew build connectedCheck

notifications:
  email:
    - email@example.com