matrix:
  include:
    - language: python
      python: 3.6
      dist: xenial
      sudo: required
      env: DISPLAY=':99.0'
      addons:
        postgresql: "9.5"
        chrome: stable
        apt:
          packages:
            - chromium-chromedriver
      services:
        - postgresql
      install:
        - pip install -r requirements.txt
        - pip install coverage robotframework-djangolibrary
      before_script:
        - sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
        - sleep 3
        - psql -c 'create database timebank_app;' -U postgres
        - psql -c "CREATE USER timebank WITH PASSWORD 'DEBUG';" -U postgres
        - psql -c "ALTER USER timebank CREATEDB;" -U postgres
      script:
        - pylint timebank_site/
        - python timebank_site/manage.py makemigrations
        - python timebank_site/manage.py migrate
        - python timebank_site/manage.py migrate --run-syncdb
        - coverage run timebank_site/manage.py test timebank_app.tests
        - coverage report --omit="*site-packages*","*tests*" --skip-covered
        - robot --variable BROWSER:headlesschrome --variable SANDBOX:--no-sandbox timebank_site/timebank_app/tests/
        - cat /home/travis/build/SombiriX/TimeBank/log.html
        - cat selenium-screenshot-1.png | base64

    # - language: node_js
    #   node_js:
    #     - "node"
    #   before_install:
    #     -  cd timebank_frontend
    #   cache:
    #     directories:
    #       - "node_modules"
    #   install:
    #     - npm install
    #   script:
    #     - npm run test:unit
    #     # - npm run test:e2e
    #     # - npm run build

notifications:
  email:
    - email@example.com