# Generated by Django 2.1 on 2018-09-08 06:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timebank_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='stop',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interval',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='timebank_app.Task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='last_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='timebank_app.Task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='task_notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='tasklist',
            field=models.ManyToManyField(blank=True, related_name='_task_tasklist_+', to='timebank_app.Task'),
        ),
    ]
