# Generated by Django 2.1.1 on 2018-09-17 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timebank_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interval',
            name='author',
        ),
    ]
