# Generated by Django 2.1 on 2018-09-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timebank_app', '0002_auto_20180908_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='stop',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_added',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
