# Generated by Django 2.1 on 2018-09-08 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timebank_app', '0003_auto_20180908_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timebank_app.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasklist',
            field=models.ManyToManyField(blank=True, null=True, related_name='_task_tasklist_+', to='timebank_app.Task'),
        ),
    ]
