# Generated by Django 2.1 on 2018-09-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timebank_app', '0004_auto_20180908_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tasklist',
            field=models.ManyToManyField(blank=True, related_name='_task_tasklist_+', to='timebank_app.Task'),
        ),
    ]
