# Generated by Django 2.1 on 2018-09-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timebank_app', '0006_auto_20180913_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='twentyFourClock',
            field=models.BooleanField(default=False),
        ),
    ]
