# Generated by Django 2.1 on 2018-09-16 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timebank_app', '0007_user_twentyfourclock'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_intervals', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
